services:
  - type: web
    name: medusa-backend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.wfdlvqkadrveigtushjh:QsefQsefQsefhelo12345@aws-0-eu-central-1.pooler.supabase.com:5432/postgres
      - key: REDIS_URL
        fromService:
          type: redis
          name: medusa-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: PORT
        value: 9000

  - type: redis
    name: medusa-redis
    plan: free
    ipAllowList: [] 